---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: hc-v12-bands-service
spec:
  selector:
    app: hc-v12-bands
  ports:
    - name: http
      port: 5102
      targetPort: 5102
  type: NodePort
